version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 10
      labels:
          - dependencies

    - package-ecosystem: npm
      directory: /docs
      schedule:
          interval: monthly
      labels: []
      ignore:
          - dependency-name: '*'
