name: Trunk Code Quality setup
description: Set up dependencies for Trunk Code Quality

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@v4 # zizmor: ignore[unpinned-uses]
          with:
              version: 10

        - name: Setup Node.js
          uses: actions/setup-node@v4 # zizmor: ignore[unpinned-uses]
          with:
              node-version: '22'

        - name: Install Root NodeJS dependencies
          shell: bash
          run: |
              pnpm install --frozen-lockfile

        - name: Install Docs NodeJS dependencies
          shell: bash
          working-directory: docs
          run: |
              pnpm install --frozen-lockfile
