name: Trunk Code Quality setup
description: Set up dependencies for Trunk Code Quality
runs:
    using: composite
    steps:
        - name: Install Root NodeJS dependencies
          shell: bash
          run: npm install
