name: Coveralls

permissions:
    contents: read
    packages: read

on:
    schedule:
        # Runs at 00:00 on Sunday
        - cron: 0 0 * * 0
    workflow_dispatch: # Allows manual triggering

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20, 22]
        steps:
            - name: Checkout
              uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
              with:
                  persist-credentials: false
                  token: ${{ secrets.ACTIONS_KEY }}

            - uses: pnpm/action-setup@v4 # zizmor: ignore[unpinned-uses]
              with:
                  version: 10

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4 # zizmor: ignore[unpinned-uses]
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Test
              run: pnpm test

            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v2 # zizmor: ignore[unpinned-uses]
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: node-${{ matrix.node-version }}
                  parallel: true
              if: matrix.node-version == '22'

            - name: Cache dependencies
              uses: actions/cache@v4 # zizmor: ignore[unpinned-uses]
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-${{ matrix.node-version }}-
                      ${{ runner.os }}-node-

    finish-coverage:
        needs: build
        runs-on: ubuntu-latest
        if: ${{ always() }}
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@v2 # zizmor: ignore[unpinned-uses]
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
